---
linters:
  BorderZero:
    enabled: true
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  DeclarationOrder:
    enabled: false
  DuplicateProperty:
    enabled: true
  EmptyLineBetweenBlocks:
    enabled: false
  FinalNewline:
    enabled: false
  HexLength:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  Shorthand:
    enabled: true
  SingleLinePerSelector:
    enabled: false
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
  SpaceAroundOperator:
    enabled: false
  StringQuotes:
    enabled: false
  TrailingSemicolon:
    enabled: false
  TrailingWhitespace:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
  ZeroUnit:
    enabled: false
