files:
  include: '**/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 1
  clean-import-paths: 1
  empty-line-between-blocks: 1
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: 1
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 1
  hex-length:
    - 1
    - style: long
  hex-notation: 1
  indentation: 1
  leading-zero:
    - 1
    - include: true
  mixin-name-format: 1
  mixins-before-declarations: 1
  nesting-depth: 0
  no-color-keyword: 1
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-ids: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-zero: 1
  no-transition-all: 0
  placeholder-name-format: 1
  property-sort-order: 0
  quotes:
    - 1
    - style: double
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon: 1
  space-after-comma: 1
  space-before-bang:
    - 1
    - include: true
  space-before-brace: 1
  space-between-parens: 1
  trailing-semicolon: 1
  variable-name-format: 1
  zero-unit: 1
